### ISSUE TITLE
No translations for ... (with yaml references)

### ISSUE THREAD

**Issue by gingerlime** [airblade/vim-localorie#5]
It's probably way too much to ask, but I noticed that when we use yaml references, I'm getting "No translations for...".

For example:

```yaml
en:
  payment:
    subscription:
      faq: &pricing_faq
        question: a question
    stripe_subscription:
      faq:
        <<: *pricing_faq
```

When I'm inside `app/views/payment/stripe_subscription.html.haml` and look up a key like `.faq.question`

Is there a way to make it work?
